### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by DavidLemayian** [Code4SA/censusreporter#61]
So I was just poking around and can't find how to ping WaziMap \ CensusReporter via an API. 

I did though see [this in CensusReporter docs](https://github.com/censusreporter/censusreporter#getting-data-from-our-api-the-basics). Is it implemented in a similar way in WaziMap?

**Comment by longhotsummer** [comment]
Is there a particular piece of data you're looking for?

We support the part of the API that is required for the distribution and map views, which is `/1.0/data/show/latest` for example: http://wazimap.co.za/api/1.0/data/show/latest?table_ids=GENDER_MARITALSTATUS&geo_ids=province-NW%2Ccountry-ZA

That API provides JSON output of table metadata, table content (data), and geography metadata and should cover most use cases.

**Comment by j-norwood-young** [comment]
Here's an example: https://github.com/Code4SA/enca-protest-map/blob/gh-pages/wazidata.py

**Comment by DavidLemayian** [comment]
@longhotsummer Thanks. No data in particular. Was wondering if I could dynamically call data from Wazimap. Is there documentation for this?

@j-norwood-young That is a great example! :+1:
