### ISSUE TITLE
Annoying popup in map view obscures the mouse pointer

### ISSUE THREAD

**Issue by adieyal** [Code4SA/censusreporter#65]
http://wazimap.co.za/data/map/?table=PARTY_VOTES_NATIONAL_2014&geo_ids=municipality|country-ZA&primary_geo_id=country-ZA#column%7CECONOMIC%20FREEDOM%20FIGHTERS%2Csumlev%7Cmunicipality

**Comment by longhotsummer** [comment]
I noticed this briefly yesterday but can't repro it. It currently looks fine in my browser. I managed to work around it by just dragging the map (assuming it's the same bug).

Can you use the help & feedback button when this happens so we can get a screenshot?

**Comment by adieyal** [comment]
will do

On 18 February 2015 at 14:42, Greg Kempe <notifications@github.com> wrote:

> I noticed this briefly yesterday but can't repro it. It currently looks
> fine in my browser. I managed to work around it by just dragging the map
> (assuming it's the same bug).
>
> Can you use the help & feedback button when this happens so we can get a
> screenshot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Code4SA/censusreporter/issues/65#issuecomment-74857778>
> .
>



-- 
Adi Eyal
Data Specialist
phone: +27 78 014 2469
skype: adieyalcas
linkedin: http://za.linkedin.com/pub/dir/Adi/Eyal
